services:
  elasticsearch:
    image: elasticsearch:8.6.1
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
    restart: always
  
  kibana:
    image: kibana:8.6.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_NAME=localhost
      - SERVER_PORT=5601
    ports:
      - 5601:5601
    networks:
      - elastic
    restart: always
    volumes:
      - ./infra/kibana.yml:/usr/share/kibana/config/kibana.yml:rw
  
networks:
  elastic:
    driver: bridge